### ISSUE TITLE
Error: This is the LanguageTool API. You have not specified any parameters

### ISSUE THREAD

**Issue by talesam** [silvio/docker-languagetool#47]
Hello, I'm trying to use this docker in my collabora which is on nextcloud, I'm going to put the docker log and my docker-compose config, everything seems to be OK, but I don't see the languagetool inside the collabora.

### Log docker languagetool
```
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
2023-04-24 17:06:45.152 +0000 INFO  org.languagetool.server.LanguageToolHttpHandler Handled request in 2ms; sending code 400
2023-04-24 17:07:17.879 +0000 INFO  org.languagetool.server.LanguageToolHttpHandler Handling POST /v2/check
2023-04-24 17:07:17.879 +0000 INFO  org.languagetool.server.LanguageToolHttpHandler An error has occurred: 'Missing 'text' or 'data' parameter', sending HTTP code 400. Access from 189.83.32.28, HTTP user agent: curl/8.0.1, User agent param: null, Referrer: null, language: en-US, h: 1, r: 12, time: 0m: ALL, l: DEFAULT, Stacktrace follows:org.languagetool.server.BadRequestException: Missing 'text' or 'data' parameter
	at org.languagetool.server.ApiV2.handleCheckRequest(ApiV2.java:165)
	at org.languagetool.server.ApiV2.handleRequest(ApiV2.java:84)
	at org.languagetool.server.LanguageToolHttpHandler.handle(LanguageToolHttpHandler.java:185)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:93)
	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:96)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:717)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:93)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:689)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
2023-04-24 17:07:17.880 +0000 INFO  org.languagetool.server.LanguageToolHttpHandler Handled request in 1ms; sending code 400
2023-04-24 17:08:37.832 +0000 INFO  org.languagetool.server.LanguageToolHttpHandler Handling POST /v2/check
2023-04-24 17:08:37.832 +0000 INFO  org.languagetool.server.LanguageToolHttpHandler An error has occurred: 'Missing 'text' or 'data' parameter', sending HTTP code 400. Access from 189.83.32.28, HTTP user agent: curl/8.0.1, User agent param: null, Referrer: null, language: en-US, h: 1, r: 13, time: 0m: ALL, l: DEFAULT, Stacktrace follows:org.languagetool.server.BadRequestException: Missing 'text' or 'data' parameter
	at org.languagetool.server.ApiV2.handleCheckRequest(ApiV2.java:165)
	at org.languagetool.server.ApiV2.handleRequest(ApiV2.java:84)
	at org.languagetool.server.LanguageToolHttpHandler.handle(LanguageToolHttpHandler.java:185)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:93)
	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:96)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:717)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:93)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:689)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
2023-04-24 17:08:37.833 +0000 INFO  org.languagetool.server.LanguageToolHttpHandler Handled request in 1ms; sending code 400
2023-04-24 17:10:32.723 +0000 INFO  org.languagetool.server.LanguageToolHttpHandler Handling POST /v2/check
2023-04-24 17:10:32.724 +0000 INFO  org.languagetool.server.LanguageToolHttpHandler An error has occurred: 'Missing 'text' or 'data' parameter', sending HTTP code 400. Access from 189.83.32.28, HTTP user agent: HTTPie/3.2.1, User agent param: null, Referrer: null, language: null, h: 1, r: 14, time: 0m: ALL, l: DEFAULT, Stacktrace follows:org.languagetool.server.BadRequestException: Missing 'text' or 'data' parameter
	at org.languagetool.server.ApiV2.handleCheckRequest(ApiV2.java:165)
	at org.languagetool.server.ApiV2.handleRequest(ApiV2.java:84)
	at org.languagetool.server.LanguageToolHttpHandler.handle(LanguageToolHttpHandler.java:185)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:93)
	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:96)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:717)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:93)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:689)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
2023-04-24 17:10:32.724 +0000 INFO  org.languagetool.server.LanguageToolHttpHandler Handled request in 1ms; sending code 400
2023-04-24 17:11:21.546 +0000 INFO  org.languagetool.server.LanguageToolHttpHandler Handling POST /v2/check
2023-04-24 17:11:21.547 +0000 INFO  org.languagetool.server.LanguageToolHttpHandler An error has occurred: 'Missing 'text' or 'data' parameter', sending HTTP code 400. Access from 189.83.32.28, HTTP user agent: HTTPie/3.2.1, User agent param: null, Referrer: null, language: null, h: 1, r: 15, time: 1m: ALL, l: DEFAULT, Stacktrace follows:org.languagetool.server.BadRequestException: Missing 'text' or 'data' parameter
	at org.languagetool.server.ApiV2.handleCheckRequest(ApiV2.java:165)
	at org.languagetool.server.ApiV2.handleRequest(ApiV2.java:84)
	at org.languagetool.server.LanguageToolHttpHandler.handle(LanguageToolHttpHandler.java:185)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:93)
	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:96)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:717)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:93)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:689)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
2023-04-24 17:11:21.548 +0000 INFO  org.languagetool.server.LanguageToolHttpHandler Handled request in 2ms; sending code 400
2023-04-24 17:12:23.199 +0000 INFO  org.languagetool.server.LanguageToolHttpHandler Handling POST /v2/check
2023-04-24 17:12:23.200 +0000 INFO  org.languagetool.server.LanguageToolHttpHandler An error has occurred: 'Missing 'text' or 'data' parameter', sending HTTP code 400. Access from 189.83.32.28, HTTP user agent: curl/8.0.1, User agent param: null, Referrer: null, language: en-US, h: 1, r: 16, time: 1m: ALL, l: DEFAULT, Stacktrace follows:org.languagetool.server.BadRequestException: Missing 'text' or 'data' parameter
	at org.languagetool.server.ApiV2.handleCheckRequest(ApiV2.java:165)
	at org.languagetool.server.ApiV2.handleRequest(ApiV2.java:84)
	at org.languagetool.server.LanguageToolHttpHandler.handle(LanguageToolHttpHandler.java:185)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:93)
	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:96)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:717)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:93)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:689)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
2023-04-24 17:12:23.200 +0000 INFO  org.languagetool.server.LanguageToolHttpHandler Handled request in 1ms; sending code 400
2023-04-24 17:12:41.717 +0000 INFO  org.languagetool.server.LanguageToolHttpHandler Handling POST /v2/check
2023-04-24 17:12:41.718 +0000 INFO  org.languagetool.server.LanguageToolHttpHandler An error has occurred: 'Missing 'text' or 'data' parameter', sending HTTP code 400. Access from 189.83.32.28, HTTP user agent: curl/8.0.1, User agent param: null, Referrer: null, language: pt-BR, h: 1, r: 17, time: 0m: ALL, l: DEFAULT, Stacktrace follows:org.languagetool.server.BadRequestException: Missing 'text' or 'data' parameter
	at org.languagetool.server.ApiV2.handleCheckRequest(ApiV2.java:165)
	at org.languagetool.server.ApiV2.handleRequest(ApiV2.java:84)
	at org.languagetool.server.LanguageToolHttpHandler.handle(LanguageToolHttpHandler.java:185)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:93)
	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:96)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:717)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:93)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:689)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
2023-04-24 17:12:41.718 +0000 INFO  org.languagetool.server.LanguageToolHttpHandler Handled request in 1ms; sending code 400
```

### docker-compose.yml
```
version: '3.9'

services:
  collabora:
    container_name: collabora
    image: collabora/code:latest
    restart: always
    environment:
      - username=admin
      - password=MYPASS
      - aliasgroup1=https://collabora.XXX.org:443,https://cloud.talesam.org:443
      - extra_params=-o:welcome.enable=false
      - dictionaries=en_US es_ES pt_BR pt_PT
      - extra_params=-o:ssl.enable=false
      - extra_params=-o:ssl.termination=false
      - extra_params=-o:languagetool.enabled=true
      - extra_params=-o:languagetool.base_url=http://IP_SERVER:8010/v2
    expose:
      - 9980
    networks:
      t4l35-net:
  
  languagetool:
    container_name: languagetool
    image: collabora/languagetool:latest
    restart: always
    cap_drop:
      - ALL
    user: "65534:65534"
    read_only: true
    environment:
      - EXTRAOPTIONS=-Xmx382M
    volumes:
      - type: bind
        source: /var/tmp/languagetool
        target: /tmp
    mem_limit: 412m
    memswap_limit: 500m
    ports:
      - "8010:8010"
    networks:
      t4l35-net:
  
networks:
  t4l35-net:
    name: t4l35-net
```

**If I run URL: http://IP_SERVER:8010/v2 appears**
```
Error: This is the LanguageTool API. You have not specified any parameters. Please see https://languagetool.org/http-api/swagger-ui/#/default
```

```
❯ curl -X POST \
     -H "Content-Type: text/plain" \
     --data "This is a test." \
     "http://144.22.139.77:8010/v2/check?language=en-US"

Error: Missing 'text' or 'data' parameter% 
```

**Comment by silvio** [comment]
Hi @talesam.

Sorry, I don't think I can help you. I know that Collabora forked their docker images from this repository (silvio/docker-languagetools from docker hub perspective) at some point, which is perfectly fine, but I'm not sure what changes they made. At least I don't see the Collabora fork in my network view.
I can't help you here right now.

**Comment by JOduMonT** [comment]
I know it's an old and close issue; but
@talesam; lately I tried to ran the Collabora image and didn't succeed
while it worked perfectly fine with silvio and erikvl87.

- the `/v2/` instead of `/api/` is definitely a must in any case.
